---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
ms.openlocfilehash: ed49e96624ae332d59005c9e7ee117d19d8ab752
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 02/17/2020
ms.locfileid: "77419717"
---
# <a name="c6318"></a>C6318

> Upozornění C6318: nesprávně definovaná __try/\__except: použijte konstantu EXCEPTION_CONTINUE_SEARCH nebo jinou konstantu, která se vyhodnotí jako nula ve výrazu filtru výjimky. Kód v bloku obslužné rutiny výjimky není proveden.

Toto upozornění znamená, že pokud dojde k výjimce v chráněném bloku této strukturované obslužné rutiny výjimek, výjimka nebude zpracována, protože ve výrazu filtru výjimky je použit konstantní `EXCECPTION_CONTINUE_SEARCH`.

Tento kód je ekvivalentní chráněnému bloku bez bloku obslužných rutin výjimek, protože blok obslužné rutiny není spuštěn.

## <a name="example"></a>Příklad

Následující kód vygeneruje toto upozornění:

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning C6318
  {
    puts("Exception Occurred");
  }
}
```

Chcete-li toto upozornění opravit, použijte následující kód:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Viz také

[try-except – příkaz](/cpp/cpp/try-except-statement)
