---
title: C6322
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6322
helpviewer_keywords:
- C6322
ms.assetid: fb23d2b1-b2a0-465c-8bf5-ec039c6c7757
ms.openlocfilehash: 47e65bfa5b350f298bf26e739a35b0f8ff4c517c
ms.sourcegitcommit: 7bea0420d0e476287641edeb33a9d5689a98cb98
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 02/17/2020
ms.locfileid: "77419689"
---
# <a name="c6322"></a>C6322

> Upozornění C6322: prázdný blok _except

Tato zpráva znamená, že v bloku _except není žádný kód. V důsledku toho může dojít k neošetřeným výjimkám.

## <a name="example"></a>Příklad

Následující kód vygeneruje toto upozornění:

```cpp
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void fd(char *pch)
{
   __try
   {
     // exception rasied if pch is null
     *pch= 0 ;
   }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION)
   {
   }
}
```

Chcete-li toto upozornění opravit, použijte následující kód:

```cpp
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void f(char *pch)
{
   __try
   {
     // exception rasied if pch is null
    *pch= 0 ;
   }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
     // code to handle exception
     puts("Exception Occurred");
   }
}
```

## <a name="see-also"></a>Viz také

[try-except – příkaz](/cpp/cpp/try-except-statement)
